version: '3'

services:
  cockroachdb:
    image: cockroachdb/cockroach:latest
    ports:
      - 26257:26257
      - 8080:8080
    environment:
      - COCKROACH_DATABASE=app
      - COCKROACH_USER=root
    volumes:
      - cockroach-volume:/cockroach/cockroach-data
    command: start-single-node --insecure
  datadog-agent:
    image: datadog/agent:latest
    ports:
      - 8126:8126
    environment:
      - DD_API_KEY=${DATADOG_API_KEY}
      - DD_ENV=${DD_ENV}
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_CONTAINER_EXCLUDE=name:datadog-agent
      - DD_RUNTIME_METRICS_ENABLED=true
      - DD_LOGS_INJECTION=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  cockroach-volume:
